export const FETCH_CONTENT = 'FETCH_CONTENT';
export const FETCH_CONTENT_SUCCEEDED = 'FETCH_CONTENT_SUCCEEDED';
export const FETCH_CONTENT_FAILED = 'FETCH_CONTENT_FAILED';
export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';